name: Build and Upload ROM

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Marsdev
        uses: i3h/download-release-asset@v1
        with:
          owner: andwn
          repo: marsdev
          tag: '2022.10'
          file: mars-2022.10-linux-x64.tar.xz

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10

      - name: Build ROM
        env:
          MARSDEV: ${{ github.workspace }}/mars
        run: |
          tar -xvf mars-2022.10-linux-x64.tar.xz
          echo TIMESTAMP=$(date +%s) >> $GITHUB_ENV
          ./scripts/mars/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.TIMESTAMP }}
          path: |
            ./out.bin
            ./symbol.txt
          if-no-files-found: error