name: Build and Upload ROM

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: code
          lfs: true

      - name: Checkout Marsdev
        uses: actions/checkout@v3
        with:
          repository: andwn/marsdev.git
          path: mars
          ref: '2022.10'

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10

      - name: Build ROM
        env:
          MARSDEV: ${{ github.workspace }}/mars
        run: |
          echo TIMESTAMP=$(date +%s) >> $GITHUB_ENV
          ./code/scripts/mars/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.TIMESTAMP }}
          path: |
            ./code/out.bin
            ./code/symbols.txt
          if-no-files-found: error